# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sampleTopics <- function(word_ids, topics, model) {
    .Call(`_TidyMallet_sampleTopics`, word_ids, topics, model)
}

